Algoritmo "semnome"

Var
numero: inteiro


Inicio
escreval("1 - Cadastrar")
escreval("2 - Alterar")
escreval("3 - excluir")
escreva("Digite a opção: ")
leia(numero)
escolha (numero)

caso 1
     escreval("Iniciando cadastro. . .")
caso 2
     escreval("Alterando. . .")
caso 3
     escreval("Excluindo. . .")
outrocaso
escreval("Opção inválida")


  fimescolha
   Fimalgoritmo